### ISSUE TITLE
Missing .wt-block-content-gedcom_block before .icon-indis (icons.css:119)

### ISSUE THREAD

**Issue by raaspt** [ekdahl/webtrees-github-theme#13]
On `/resources/css/icons.css#L119`, please consider replacing
`.card-body.wt-block-content.wt-block-content-gedcom_block a i::before, .icon-indis, .wt-block-content-gedcom_block .icon-pedigree {`
by
`.card-body.wt-block-content.wt-block-content-gedcom_block a i::before, .wt-block-content-gedcom_block .icon-indis, .wt-block-content-gedcom_block .icon-pedigree {`
Thanks!

**Comment by ekdahl** [comment]
Can you enlighten me about what issue it solves?

**Comment by ekdahl** [comment]
I still can't see it. Can you illustrate with a screenshot?

**Comment by raaspt** [comment]
Please ignore as I had a conflicting CSS. Sorry.
