### ISSUE TITLE
Styling for suggestion popup

### ISSUE THREAD

**Issue by ekdahl** [ekdahl/webtrees-github-theme#4]
Reported in forum post [here](https://www.webtrees.net/index.php/forum/4-customising/39123-trying-to-make-a-dark-theme#106949).
![capturematchcodewithblack](https://github.com/user-attachments/assets/2cebcc33-2abe-4881-aef6-45df8b67f240)

**Comment by HerzScheisse** [comment]
Hi @ekdahl 

i want to follow up this issue...

while your fixe works with "mouseover" it doesnt if i type in and use arrow down mainboard key...

![2024-10-08 20_18_44-Johann Samuel Kind - Geburt – Familienforschung eisold family – Mozilla Firefox](https://github.com/user-attachments/assets/3ee340d6-ad6a-4a6c-bbd2-bd075601b93e)

tested on latest version and with both light themes
